class FunctionIds:
    ManageCustomersByCustomers = "Manage Customers by Customers"
    ManageCustomersByEmployees = "Manage Customers by Employees"
    ManageVehicle = "Manage Vehicles"
    ManageVehicleTypes = "Manage Vehicle Types"
    ManageContractsByCustomers = "Manage Contracts by Customers"
    ManageContractsByEmployees = "Manage Contracts by Employees"
    ManageClaimsByCustomers = "Manage Claims by Customers"
    ManageClaimsByEmployees = "Manage Claims by Employees"
    ManageExpenses = "Manage Expenses"
    ManageEmployeesByAdmin = "Manage Employees by Admin"
    ManageEmployeesByEmployees = "Manage Employees by Employees"
    ManageGroupsUsers = "Manage Groups users"
    ManageInsuranceCategories = "Manage Insurance Categories"
    ManageInsurancePriceList = "Manage Insurance Price List"
    ManageHome = "Manage Home Page"

class ActionIds:
    View = "View"
    Create = "Create"
    Edit = "Edit"
    Delete = "Delete"
    Download = "Download"
    Print = "Print"
    Export = "Export"