class FunctionIds:
    ManageCustomers = "Manage Customers"
    ManageVehicles = "Manage Vehicles"
    ManageVehicleTypes = "Manage Vehicle types"
    ManageContracts = "Manage Contracts"
    ManageClaims = "Manage Claims"
    ManageExpenses = "Manage Expenses"
    ManageEmployees = "Manage Employees"
    ManageGroupsUsers = "Manage Groups users"
    ManageInsuranceCategories = "Manage Insurance Categories"
    ManageInsurancePriceList = "Manage Insurance Price List"

class ActionIds:
    View = "View"
    Create = "Create"
    Edit = "Edit"
    Delete = "Delete"
    Download = "Download"
    Print = "Print"
    Export = "Export"